export const FETCH_POKEMON_START = "FETCH_POKEMON_START";
export const FETCH_POKEMON_SUCCESS = "FETCH_POKEMON_SUCCESS";
export const FETCH_POKEMON_FAIL = "FETCH_POKEMON_FAIL";

export const ADD_POKEMON_TO_FAVORITES = "ADD_POKEMON_TO_FAVORITES";
export const REMOVE_POKEMON_FROM_FAVORITES = "REMOVE_POKEMON_FROM_FAVORITES";
