export const ADD_ITEM = "ADD_ITEM";
export const REMOVE_ITEM = "REMOVE_ITEM";

export const FETCH_POKEMONS_START = "FETCH_POKEMONS_START";
export const SEARCH_FOR_ITEM = "SEARCH_FOR_ITEM";
export const CLEAR_ITEMS = "CLEAR_ITEMS";
